#!/bin/bash -ex
project=icingaweb2
repoprefix=icinga

source jenkins-scripts/modules/prepare_build_job

# Build the source tarball
git archive --format=tar --prefix=$project/ -o $project.tar HEAD
md5sum $project.tar

# Append the Debian pkg files
rm -rf pkg-$project
success=0
for i in $(seq 10); do
  if git clone git://github.com/Icinga/pkg-$project-debian.git pkg-$project; then
    success=1
    break;
  fi
  sleep 10
done
if [ "0" ==  "$success" ]; then
  exit 1
fi


case "$distro" in
ubuntu-xenial)
  (cd pkg-icingaweb2; git checkout ubuntu_xenial)
  ;;
ubuntu-trusty)
  (cd pkg-icingaweb2; git checkout ubuntu_trusty)
  ;;
ubuntu-precise)
  (cd pkg-icingaweb2; git checkout ubuntu_precise)
  ;;
debian-jessie)
  (cd pkg-icingaweb2; git checkout debmon-jessie)
  ;;
debian-wheezy)
  (cd pkg-icingaweb2; git checkout debmon-wheezy)
  ;;
ubuntu-*|raspbian-*|debian-squeeze)
  (cd pkg-icingaweb2; git checkout legacy)
  ;;
esac

echo "3.0 (native)" > pkg-$project/debian/source/format

tar --append -f $project.tar --transform "s@^@$project/@" -C pkg-$project debian
gzip -n < $project.tar > $project.tar.gz
md5sum $project.tar.gz

source jenkins-scripts/modules/build_deb
package_type=deb
source jenkins-scripts/modules/repo_aptly

#pushd DEBS
#cat >dput.cf <<DPUT
#[icinga]
#fqdn = packages.icinga.org
#incoming = /home/debianrepo/`echo $distro | cut -f1 -d-`/incoming/
#method = local
#allowed_distributions = icinga-.*
#allow_unsigned_uploads = 1
#DPUT
#
#dput -c dput.cf icinga *.changes
#popd
